services: 
    adminer:
        image: adminer:latest
        container_name: AMT_adminer
        depends_on:
            - db
        ports:
            - 8082:8080
        environment:
            MYSQL_ROOT_PASSWORD: root
        networks:
            - default
    db:
        image: mysql:latest
        container_name: AMT_mysql
        command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: db_flipflop
            MYSQL_USER: flipflop
            MYSQL_PASSWORD: FlipFlop1234
            MYSQL_ROOT_PASSWORD: FlipFlop1234
        #volumes:
            #- ../data/scripts:/docker-entrypoint-initdb.d
        networks:
            - default
            